### ISSUE TITLE
Wishlist fails when empty

### ISSUE THREAD

**Issue by evest** [OXXAS/CommerceStarterKit#18]
When the wishlist is empty, the loading image just keeps spinning, and the angular call fails with:

```
{"Message":"An error has occurred.","ExceptionMessage":"ArgumentOutOfRange_Index
Parameter name: index","ExceptionType":"System.ArgumentOutOfRangeException","StackTrace":"   
   at Mediachase.Commerce.Storage.StorageCollectionBase.System.Collections.IList.get_Item(Int32 index)
   at Mediachase.Commerce.Storage.MetaStorageCollectionBase`1.get_Item(Int32 index)
   at OxxCommerceStarterKit.Core.Services.CartService.UpdateShipping(String name) in s:\\buildAgent-work\\OxxStarterKitGit\\src\\common\\Core\\Services\\CartService.cs:line 263
   at OxxCommerceStarterKit.Web.Api.CartController.GetCart(String cart) in s:\\buildAgent-work\\OxxStarterKitGit\\src\\web\\Api\\CartController.cs:line 65
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__0.MoveNext()"}
```
The call goes is missing the language:
`/undefined/api/cart/getCart?_=1421750723692&cart=WishList`
Expected: 
`/en/api/cart/getCart?_=1421750723692&cart=WishList`

**Comment by evest** [comment]
This has been fixed a long time ago.
